namespace LoopRelay.Roadmap.Cli.Primitives.State;

internal enum RoadmapState
{
    CoreReady,
    BootstrapRoadmapCompletionContext,
    RoadmapCompletionContextReady,
    SelectNextStrategicInitiative,
    ExistingEpicSelected,
    NewEpicProposed,
    SplitEpicProposed,
    EpicPreparationAudit,
    RealignEpic,
    ReimagineEpic,
    RetireEpic,
    EvidenceBlocked,
    EvidenceGathering,
    CreateNewEpic,
    SplitEpic,
    SplitChildSelection,
    ActiveEpicReady,
    GenerateMilestoneDeepDives,
    MilestoneSpecsReady,
    GenerateOperationalContext,
    OperationalContextReady,
    GenerateExecutionPrompt,
    ExecutionPromptReady,
    ExecutionLoop,
    ExecutionBlocked,
    EpicCompletionDetected,
    CompletionEvaluationAndContextUpdate,
    StrategicInvestigationRequired,
    RoadmapRevisionRequired,
    NoSuitableInitiative,
    Completed,
    Failed,
    Cancelled,
}
