using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CommandCenter.Backend.Tests;

internal sealed record ContractGenerationIr(
    string ContractId,
    string ContractName,
    ContractGenerationShape RootShape,
    IReadOnlyList<ContractGenerationField> Fields);

internal sealed record ContractGenerationField(
    string Path,
    ContractGenerationShapeKind ShapeKind,
    string TypeScriptType);

internal sealed record ContractGenerationShape(
    ContractGenerationShapeKind Kind,
    IReadOnlyList<ContractGenerationShape> Items,
    IReadOnlyList<ContractGenerationProperty> Properties);

internal sealed record ContractGenerationProperty(
    string Name,
    ContractGenerationShape Shape);

internal enum ContractGenerationShapeKind
{
    Array,
    Object,
    String,
    Number,
    Boolean,
    Null
}

internal static class ContractGenerationIrBuilder
{
    public static ContractGenerationIr Build(string contractId, string contractName, JsonElement source)
    {
        ContractGenerationShape rootShape = ReadShape(source);
        return new ContractGenerationIr(
            contractId,
            contractName,
            rootShape,
            EnumerateFields("$", rootShape).ToArray());
    }

    private static ContractGenerationShape ReadShape(JsonElement element)
    {
        return element.ValueKind switch
        {
            JsonValueKind.Array => new ContractGenerationShape(
                ContractGenerationShapeKind.Array,
                element.EnumerateArray().Take(1).Select(ReadShape).ToArray(),
                []),
            JsonValueKind.Object => new ContractGenerationShape(
                ContractGenerationShapeKind.Object,
                [],
                element.EnumerateObject()
                    .Select(property => new ContractGenerationProperty(property.Name, ReadShape(property.Value)))
                    .ToArray()),
            JsonValueKind.String => Leaf(ContractGenerationShapeKind.String),
            JsonValueKind.Number => Leaf(ContractGenerationShapeKind.Number),
            JsonValueKind.True or JsonValueKind.False => Leaf(ContractGenerationShapeKind.Boolean),
            JsonValueKind.Null => Leaf(ContractGenerationShapeKind.Null),
            _ => throw new InvalidOperationException($"Unsupported contract JSON value kind {element.ValueKind}.")
        };
    }

    private static IEnumerable<ContractGenerationField> EnumerateFields(string path, ContractGenerationShape shape)
    {
        yield return new ContractGenerationField(path, shape.Kind, ToTypeScriptType(shape));

        if (shape.Kind == ContractGenerationShapeKind.Array && shape.Items.Count > 0)
        {
            foreach (ContractGenerationField field in EnumerateFields($"{path}[]", shape.Items[0]))
            {
                yield return field;
            }
        }

        if (shape.Kind == ContractGenerationShapeKind.Object)
        {
            foreach (ContractGenerationProperty property in shape.Properties)
            {
                foreach (ContractGenerationField field in EnumerateFields($"{path}.{property.Name}", property.Shape))
                {
                    yield return field;
                }
            }
        }
    }

    private static ContractGenerationShape Leaf(ContractGenerationShapeKind kind)
    {
        return new ContractGenerationShape(kind, [], []);
    }

    private static string ToTypeScriptType(ContractGenerationShape shape)
    {
        return shape.Kind switch
        {
            ContractGenerationShapeKind.Array => shape.Items.Count == 0
                ? "unknown[]"
                : $"{ToTypeScriptType(shape.Items[0])}[]",
            ContractGenerationShapeKind.Object => "Record<string, unknown>",
            ContractGenerationShapeKind.String => "string",
            ContractGenerationShapeKind.Number => "number",
            ContractGenerationShapeKind.Boolean => "boolean",
            ContractGenerationShapeKind.Null => "null",
            _ => throw new InvalidOperationException($"Unsupported contract shape kind {shape.Kind}.")
        };
    }
}

internal static class ContractGenerationIrSerializer
{
    public static string Serialize(ContractGenerationIr ir)
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web)
        {
            WriteIndented = true
        };
        options.Converters.Add(new JsonStringEnumConverter());

        return JsonSerializer.Serialize(ir, options) + Environment.NewLine;
    }
}

internal static class ContractTypeScriptMetadataGenerator
{
    public static string Generate(ContractGenerationIr ir)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from the Contract Oracle fixture. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine($"export const repositoryDashboardContractId = '{ir.ContractId}' as const");
        builder.AppendLine($"export const repositoryDashboardContractName = '{ir.ContractName}' as const");
        builder.AppendLine();
        builder.AppendLine("export type RepositoryDashboardContractField = {");
        builder.AppendLine("  path: string");
        builder.AppendLine("  shapeKind: RepositoryDashboardContractShapeKind");
        builder.AppendLine("  typeScriptType: string");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export type RepositoryDashboardContractShapeKind =");

        foreach (ContractGenerationShapeKind kind in Enum.GetValues<ContractGenerationShapeKind>())
        {
            builder.AppendLine($"  | '{ToCamelCase(kind.ToString())}'");
        }

        builder.AppendLine();
        builder.AppendLine("export const repositoryDashboardContractFields = [");

        foreach (ContractGenerationField field in ir.Fields)
        {
            builder.AppendLine("  {");
            builder.AppendLine($"    path: '{field.Path}',");
            builder.AppendLine($"    shapeKind: '{ToCamelCase(field.ShapeKind.ToString())}',");
            builder.AppendLine($"    typeScriptType: '{field.TypeScriptType}',");
            builder.AppendLine("  },");
        }

        builder.AppendLine("] satisfies RepositoryDashboardContractField[]");
        return builder.ToString();
    }

    private static string ToCamelCase(string value)
    {
        return char.ToLowerInvariant(value[0]) + value[1..];
    }
}
