using CommandCenter.Decisions.Primitives;

namespace CommandCenter.Decisions.Models;

public sealed record DecisionQualityReport(
    string Id,
    Guid RepositoryId,
    DateTimeOffset GeneratedAt,
    int DecisionCount,
    int GeneratedPackageCount,
    int AcceptedCount,
    double AcceptedRate,
    int ModifiedCount,
    double ModifiedRate,
    int RejectedCount,
    double RejectedRate,
    int SupersededCount,
    double SupersededRate,
    int RecommendationDivergenceCount,
    double RecommendationDivergenceRate,
    int AlternativeUtilizationCount,
    double AlternativeUtilizationRate,
    int ReviewOnlyCount,
    double ReviewOnlyRate,
    int MinorEditCount,
    double MinorEditRate,
    int MajorRefinementCount,
    double MajorRefinementRate,
    int FullRewriteCount,
    double FullRewriteRate,
    int GenerationBypassedCount,
    double GenerationBypassedRate,
    DecisionQualityRating Rating,
    IReadOnlyList<DecisionQualityAssessment> Assessments,
    IReadOnlyList<string> Diagnostics,
    IReadOnlyList<HumanAuthoringBurdenExplanation>? HumanAuthoringBurdenExplanations = null);
