using LoopRelay.Decisions.Primitives;

namespace LoopRelay.Decisions.Models;

public sealed record DecisionProposalRevision(
    string Id,
    Guid RepositoryId,
    string ProposalId,
    DateTimeOffset CreatedAt,
    string Reason,
    IReadOnlyList<string> ChangedFields,
    string SourceProposalFingerprint,
    IReadOnlyList<DecisionSourceReference> Sources,
    string? RequestedBy = null,
    IReadOnlyList<string>? AcceptedChanges = null,
    IReadOnlyList<string>? RejectedChanges = null,
    IReadOnlyList<string>? Diagnostics = null,
    IReadOnlyList<DecisionOption>? PreviousOptions = null,
    IReadOnlyList<DecisionOption>? RetiredOptions = null,
    IReadOnlyList<DecisionAssumption>? PreviousAssumptions = null,
    IReadOnlyList<DecisionAssumption>? RetiredAssumptions = null,
    IReadOnlyList<DecisionConstraint>? Constraints = null,
    IReadOnlyList<DecisionAssumptionRevision>? AssumptionRevisions = null,
    IReadOnlyList<DecisionOptionRevision>? OptionRevisions = null,
    IReadOnlyList<DecisionTradeoffRevision>? TradeoffRevisions = null,
    IReadOnlyList<DecisionPriorityAdjustment>? PriorityAdjustments = null,
    string? PreviousRecommendationRationale = null,
    string? RevisedRecommendationRationale = null,
    string? PreviousContext = null,
    string? RevisedContext = null,
    IReadOnlyList<DecisionOption>? RevisedOptions = null,
    IReadOnlyList<DecisionTradeoff>? PreviousTradeoffs = null,
    IReadOnlyList<DecisionTradeoff>? RevisedTradeoffs = null,
    IReadOnlyList<DecisionAssumption>? RevisedAssumptions = null,
    HumanAuthoringBurden HumanAuthoringBurden = HumanAuthoringBurden.Unknown);
